language: scala

jdk: openjdk11

scala:
   - 2.13.0
   - 2.12.8
   - 2.12.7

script:
   - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
   - bash <(curl -s https://codecov.io/bash)